== Sum Project

This is a simple project to demonstrate a couple of EIPs applied using Red Hat Jboss Fuse.

Basically this project receive two values via webservice SOAP and REST and sum it saving the result in a file system.

=== Use case
. Receive two integer parameters via REST and SOAP 
. Imediatly return a "OK" String to a valid two integers values 
. Imediatly return a "NOK" String to a non valid two integers values 
. Send in background the two values to sum 
. Send the result to a Active-MQ queue
. Retrieve the result from the queue and save in a file 
. In case of the queue is unavailable, handle the error and send an email to a previously configured account 
. Mail configuration and queue names could be changed in a file outside the project

=== Build 

To build this project use:
	
	mvn clean install

=== Requirements

* Red Hat Jboss Fuse 6.3
* SMTP server. 
I used the fake-smtp.jar to mock a mail server. To run:

	java -jar resources/fake-smtp.jar 

And specify port 2525.

=== Running the application

From the Jboss Fuse CLI use:

Setup ActiveMQ
 
    jms:create -t ActiveMQ -u tcp://localhost:61616 pepe

Install features

	features:install camel-string-template
	features:install camel-jetty9
	features:install camel-script-groovy

To deploy in Fuse standalone:

	install -s mvn:com.redhat.fuse/sum/1.0

To deploy in Fuse Fabric

	mvn fabric8:deploy

To override properties, is necessary to create file called sum.cfg in $FUSE_HOME/etc directory. 

An example of an file with supported properties above:

	queueName=soma
	smtp.host=localhost
	smtp.port=2525
	smtp.to=afranco@redhat.com
	smtp.from=hodrigohamalho@gmail.com

To test the unavailable message queue, a easy way is stopping openwire connector from the ActiveMQ tab panel in the Fuse web console (Hawtio)

=== Test the route 

REST: http://localhost:8183/sum/1/2

SOAP: http://localhost:8181/cxf/Sum?wsdl

You should see a OK as result.

And inspect the file inside your $FUSE_HOME/sumDir to show the results of the sum.